FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates tzdata \
    && rm -rf /var/lib/apt/lists/*

COPY ./imuad /usr/local/bin/imuad

RUN useradd -r -u 10001 imua && \
    chown -R imua:imua /usr/local/bin/imuad

USER imua

ENTRYPOINT ["/usr/local/bin/imuad"]
