// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: imuachain/dogfood/v1/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

// QueryOptOutsToFinishRequest is request type for the Query/OptOutsToFinish RPC method.
type QueryOptOutsToFinishRequest struct {
	// epoch is the epoch to query opt-outs for.
	Epoch int64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *QueryOptOutsToFinishRequest) Reset()         { *m = QueryOptOutsToFinishRequest{} }
func (m *QueryOptOutsToFinishRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOptOutsToFinishRequest) ProtoMessage()    {}
func (*QueryOptOutsToFinishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{2}
}
func (m *QueryOptOutsToFinishRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOptOutsToFinishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOptOutsToFinishRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOptOutsToFinishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOptOutsToFinishRequest.Merge(m, src)
}
func (m *QueryOptOutsToFinishRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOptOutsToFinishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOptOutsToFinishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOptOutsToFinishRequest proto.InternalMessageInfo

func (m *QueryOptOutsToFinishRequest) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

// QueryOperatorOptOutFinishEpochRequest is request type for the Query/OperatorOptOutFinishEpoch
// RPC method.
type QueryOperatorOptOutFinishEpochRequest struct {
	// operator_acc_addr is the operator account address.
	OperatorAccAddr string `protobuf:"bytes,1,opt,name=operator_acc_addr,json=operatorAccAddr,proto3" json:"operator_acc_addr,omitempty"`
}

func (m *QueryOperatorOptOutFinishEpochRequest) Reset()         { *m = QueryOperatorOptOutFinishEpochRequest{} }
func (m *QueryOperatorOptOutFinishEpochRequest) String() string { return proto.CompactTextString(m) }
func (*QueryOperatorOptOutFinishEpochRequest) ProtoMessage()    {}
func (*QueryOperatorOptOutFinishEpochRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{3}
}
func (m *QueryOperatorOptOutFinishEpochRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOperatorOptOutFinishEpochRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOperatorOptOutFinishEpochRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOperatorOptOutFinishEpochRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOperatorOptOutFinishEpochRequest.Merge(m, src)
}
func (m *QueryOperatorOptOutFinishEpochRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryOperatorOptOutFinishEpochRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOperatorOptOutFinishEpochRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOperatorOptOutFinishEpochRequest proto.InternalMessageInfo

func (m *QueryOperatorOptOutFinishEpochRequest) GetOperatorAccAddr() string {
	if m != nil {
		return m.OperatorAccAddr
	}
	return ""
}

// QueryOperatorOptOutFinishEpochResponse is response type for the
// Query/OperatorOptOutFinishEpoch RPC method.
type QueryOperatorOptOutFinishEpochResponse struct {
	// epoch is the epoch when the operator's opt-out will finish.
	Epoch int64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *QueryOperatorOptOutFinishEpochResponse) Reset() {
	*m = QueryOperatorOptOutFinishEpochResponse{}
}
func (m *QueryOperatorOptOutFinishEpochResponse) String() string { return proto.CompactTextString(m) }
func (*QueryOperatorOptOutFinishEpochResponse) ProtoMessage()    {}
func (*QueryOperatorOptOutFinishEpochResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{4}
}
func (m *QueryOperatorOptOutFinishEpochResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryOperatorOptOutFinishEpochResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryOperatorOptOutFinishEpochResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryOperatorOptOutFinishEpochResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryOperatorOptOutFinishEpochResponse.Merge(m, src)
}
func (m *QueryOperatorOptOutFinishEpochResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryOperatorOptOutFinishEpochResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryOperatorOptOutFinishEpochResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryOperatorOptOutFinishEpochResponse proto.InternalMessageInfo

func (m *QueryOperatorOptOutFinishEpochResponse) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

// QueryUndelegationsToMatureRequest is request type for the Query/UndelegationsToMature RPC method.
type QueryUndelegationsToMatureRequest struct {
	// epoch is the epoch to query undelegations for.
	Epoch int64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *QueryUndelegationsToMatureRequest) Reset()         { *m = QueryUndelegationsToMatureRequest{} }
func (m *QueryUndelegationsToMatureRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUndelegationsToMatureRequest) ProtoMessage()    {}
func (*QueryUndelegationsToMatureRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{5}
}
func (m *QueryUndelegationsToMatureRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUndelegationsToMatureRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUndelegationsToMatureRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUndelegationsToMatureRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUndelegationsToMatureRequest.Merge(m, src)
}
func (m *QueryUndelegationsToMatureRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUndelegationsToMatureRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUndelegationsToMatureRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUndelegationsToMatureRequest proto.InternalMessageInfo

func (m *QueryUndelegationsToMatureRequest) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

// QueryUndelegationMaturityEpochRequest is request type for the Query/UndelegationMaturityEpoch
// RPC method.
type QueryUndelegationMaturityEpochRequest struct {
	// record_key is the undelegation record key. note that the UndelegationRecordKey used by the
	// delegation module is just a string converted to bytes, which we will reverse here.
	RecordKey string `protobuf:"bytes,1,opt,name=record_key,json=recordKey,proto3" json:"record_key,omitempty"`
}

func (m *QueryUndelegationMaturityEpochRequest) Reset()         { *m = QueryUndelegationMaturityEpochRequest{} }
func (m *QueryUndelegationMaturityEpochRequest) String() string { return proto.CompactTextString(m) }
func (*QueryUndelegationMaturityEpochRequest) ProtoMessage()    {}
func (*QueryUndelegationMaturityEpochRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{6}
}
func (m *QueryUndelegationMaturityEpochRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUndelegationMaturityEpochRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUndelegationMaturityEpochRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUndelegationMaturityEpochRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUndelegationMaturityEpochRequest.Merge(m, src)
}
func (m *QueryUndelegationMaturityEpochRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryUndelegationMaturityEpochRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUndelegationMaturityEpochRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUndelegationMaturityEpochRequest proto.InternalMessageInfo

func (m *QueryUndelegationMaturityEpochRequest) GetRecordKey() string {
	if m != nil {
		return m.RecordKey
	}
	return ""
}

// QueryUndelegationMaturityEpochResponse is response type for the
// Query/UndelegationMaturityEpoch RPC method.
type QueryUndelegationMaturityEpochResponse struct {
	// epoch is the epoch when the undelegation will mature.
	Epoch int64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
}

func (m *QueryUndelegationMaturityEpochResponse) Reset() {
	*m = QueryUndelegationMaturityEpochResponse{}
}
func (m *QueryUndelegationMaturityEpochResponse) String() string { return proto.CompactTextString(m) }
func (*QueryUndelegationMaturityEpochResponse) ProtoMessage()    {}
func (*QueryUndelegationMaturityEpochResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{7}
}
func (m *QueryUndelegationMaturityEpochResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryUndelegationMaturityEpochResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryUndelegationMaturityEpochResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryUndelegationMaturityEpochResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryUndelegationMaturityEpochResponse.Merge(m, src)
}
func (m *QueryUndelegationMaturityEpochResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryUndelegationMaturityEpochResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryUndelegationMaturityEpochResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryUndelegationMaturityEpochResponse proto.InternalMessageInfo

func (m *QueryUndelegationMaturityEpochResponse) GetEpoch() int64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

// QueryValidatorRequest is request type for the Query/Validator RPC method.
type QueryValidatorRequest struct {
	// cons_addr is the consensus address of the validator being queried. From the perspective of
	// this module, the acc_addr is not relevant and is thus not stored.
	ConsAddr string `protobuf:"bytes,1,opt,name=cons_addr,json=consAddr,proto3" json:"cons_addr,omitempty"`
}

func (m *QueryValidatorRequest) Reset()         { *m = QueryValidatorRequest{} }
func (m *QueryValidatorRequest) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorRequest) ProtoMessage()    {}
func (*QueryValidatorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{8}
}
func (m *QueryValidatorRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorRequest.Merge(m, src)
}
func (m *QueryValidatorRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorRequest proto.InternalMessageInfo

func (m *QueryValidatorRequest) GetConsAddr() string {
	if m != nil {
		return m.ConsAddr
	}
	return ""
}

// QueryValidatorResponse is response type for the Query/Validator RPC method.
type QueryValidatorResponse struct {
	// validator is the validator being queried.
	Validator *ImuachainValidator `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
}

func (m *QueryValidatorResponse) Reset()         { *m = QueryValidatorResponse{} }
func (m *QueryValidatorResponse) String() string { return proto.CompactTextString(m) }
func (*QueryValidatorResponse) ProtoMessage()    {}
func (*QueryValidatorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{9}
}
func (m *QueryValidatorResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryValidatorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryValidatorResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryValidatorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryValidatorResponse.Merge(m, src)
}
func (m *QueryValidatorResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryValidatorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryValidatorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryValidatorResponse proto.InternalMessageInfo

func (m *QueryValidatorResponse) GetValidator() *ImuachainValidator {
	if m != nil {
		return m.Validator
	}
	return nil
}

// QueryAllValidatorsRequest is request type for the Query/AllValidators RPC method.
type QueryAllValidatorsRequest struct {
	// pagination defines an optional pagination for the request.
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllValidatorsRequest) Reset()         { *m = QueryAllValidatorsRequest{} }
func (m *QueryAllValidatorsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllValidatorsRequest) ProtoMessage()    {}
func (*QueryAllValidatorsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{10}
}
func (m *QueryAllValidatorsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllValidatorsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllValidatorsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllValidatorsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllValidatorsRequest.Merge(m, src)
}
func (m *QueryAllValidatorsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllValidatorsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllValidatorsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllValidatorsRequest proto.InternalMessageInfo

func (m *QueryAllValidatorsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

// QueryAllValidatorsResponse is response type for the Query/AllValidators RPC method.
type QueryAllValidatorsResponse struct {
	// validators is the list of all validators.
	Validators []ImuachainValidator `protobuf:"bytes,1,rep,name=validators,proto3" json:"validators"`
	// pagination defines the pagination in the response.
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllValidatorsResponse) Reset()         { *m = QueryAllValidatorsResponse{} }
func (m *QueryAllValidatorsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllValidatorsResponse) ProtoMessage()    {}
func (*QueryAllValidatorsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_693bef596e1d2d1b, []int{11}
}
func (m *QueryAllValidatorsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllValidatorsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllValidatorsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllValidatorsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllValidatorsResponse.Merge(m, src)
}
func (m *QueryAllValidatorsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllValidatorsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllValidatorsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllValidatorsResponse proto.InternalMessageInfo

func (m *QueryAllValidatorsResponse) GetValidators() []ImuachainValidator {
	if m != nil {
		return m.Validators
	}
	return nil
}

func (m *QueryAllValidatorsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "imuachain.dogfood.v1.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "imuachain.dogfood.v1.QueryParamsResponse")
	proto.RegisterType((*QueryOptOutsToFinishRequest)(nil), "imuachain.dogfood.v1.QueryOptOutsToFinishRequest")
	proto.RegisterType((*QueryOperatorOptOutFinishEpochRequest)(nil), "imuachain.dogfood.v1.QueryOperatorOptOutFinishEpochRequest")
	proto.RegisterType((*QueryOperatorOptOutFinishEpochResponse)(nil), "imuachain.dogfood.v1.QueryOperatorOptOutFinishEpochResponse")
	proto.RegisterType((*QueryUndelegationsToMatureRequest)(nil), "imuachain.dogfood.v1.QueryUndelegationsToMatureRequest")
	proto.RegisterType((*QueryUndelegationMaturityEpochRequest)(nil), "imuachain.dogfood.v1.QueryUndelegationMaturityEpochRequest")
	proto.RegisterType((*QueryUndelegationMaturityEpochResponse)(nil), "imuachain.dogfood.v1.QueryUndelegationMaturityEpochResponse")
	proto.RegisterType((*QueryValidatorRequest)(nil), "imuachain.dogfood.v1.QueryValidatorRequest")
	proto.RegisterType((*QueryValidatorResponse)(nil), "imuachain.dogfood.v1.QueryValidatorResponse")
	proto.RegisterType((*QueryAllValidatorsRequest)(nil), "imuachain.dogfood.v1.QueryAllValidatorsRequest")
	proto.RegisterType((*QueryAllValidatorsResponse)(nil), "imuachain.dogfood.v1.QueryAllValidatorsResponse")
}

func init() { proto.RegisterFile("imuachain/dogfood/v1/query.proto", fileDescriptor_693bef596e1d2d1b) }

var fileDescriptor_693bef596e1d2d1b = []byte{
	// 858 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcf, 0x6f, 0xe3, 0x44,
	0x14, 0x8e, 0x77, 0xd9, 0x8a, 0x3c, 0x0e, 0x2b, 0x86, 0x2c, 0xa2, 0x6e, 0x09, 0x5d, 0x4b, 0x94,
	0xdd, 0x2e, 0xb1, 0x37, 0x5d, 0xd0, 0xf2, 0x73, 0x45, 0x2a, 0x91, 0xaa, 0xaa, 0xa0, 0x6d, 0x28,
	0x1c, 0xb8, 0x84, 0x89, 0x3d, 0x75, 0x2c, 0x12, 0x8f, 0xeb, 0x19, 0x47, 0x0d, 0x55, 0x2e, 0x9c,
	0x7a, 0x44, 0xe2, 0x5e, 0x71, 0xe7, 0xc2, 0x85, 0x7f, 0x80, 0x53, 0x8f, 0x95, 0xb8, 0x70, 0x42,
	0xa8, 0x41, 0xe2, 0xc2, 0x1f, 0x81, 0x3c, 0x33, 0xfe, 0xd1, 0xd6, 0x71, 0xca, 0xde, 0xdc, 0x99,
	0xf7, 0xbd, 0xf7, 0x7d, 0xf3, 0xde, 0xfb, 0x1a, 0x58, 0xf1, 0x86, 0x11, 0xb6, 0xfb, 0xd8, 0xf3,
	0x2d, 0x87, 0xba, 0x07, 0x94, 0x3a, 0xd6, 0xa8, 0x69, 0x1d, 0x46, 0x24, 0x1c, 0x9b, 0x41, 0x48,
	0x39, 0x45, 0xb5, 0x34, 0xc2, 0x54, 0x11, 0xe6, 0xa8, 0xa9, 0xaf, 0xd9, 0x94, 0x0d, 0x29, 0xb3,
	0x7a, 0x98, 0x11, 0x19, 0x6e, 0x8d, 0x9a, 0x3d, 0xc2, 0x71, 0xd3, 0x0a, 0xb0, 0xeb, 0xf9, 0x98,
	0x7b, 0xd4, 0x97, 0x19, 0xf4, 0x25, 0x15, 0x9b, 0x84, 0xe5, 0xd3, 0xeb, 0x35, 0x97, 0xba, 0x54,
	0x7c, 0x5a, 0xf1, 0x97, 0x3a, 0x5d, 0x76, 0x29, 0x75, 0x07, 0xc4, 0xc2, 0x81, 0x67, 0x61, 0xdf,
	0xa7, 0x5c, 0xe4, 0x63, 0xea, 0xd6, 0x28, 0x24, 0x9d, 0xb0, 0x93, 0x31, 0xf7, 0x0b, 0x63, 0x02,
	0x1c, 0xe2, 0xa1, 0x4a, 0x63, 0xd4, 0x00, 0xed, 0xc5, 0x4c, 0x76, 0xc5, 0x61, 0x87, 0x1c, 0x46,
	0x84, 0x71, 0x63, 0x0f, 0x5e, 0xb9, 0x74, 0xca, 0x02, 0xea, 0x33, 0x82, 0x3e, 0x80, 0x05, 0x09,
	0x7e, 0x4d, 0x5b, 0xd1, 0x1e, 0xbc, 0xb4, 0xbe, 0x6c, 0x16, 0xbd, 0x8b, 0x29, 0x51, 0x1b, 0x2f,
	0x9c, 0xfd, 0xf9, 0x46, 0xa5, 0xa3, 0x10, 0xc6, 0x13, 0x58, 0x12, 0x29, 0x77, 0x02, 0xbe, 0x13,
	0x71, 0xb6, 0x4f, 0xdb, 0x9e, 0xef, 0xb1, 0xbe, 0xaa, 0x88, 0x6a, 0x70, 0x87, 0x04, 0xd4, 0xee,
	0x8b, 0xcc, 0xb7, 0x3b, 0xf2, 0x0f, 0xe3, 0x0b, 0x78, 0x53, 0x81, 0x48, 0x88, 0x39, 0x0d, 0x25,
	0x58, 0x22, 0x3f, 0x8d, 0x23, 0x12, 0xf8, 0x1a, 0xbc, 0x4c, 0x55, 0x4c, 0x17, 0xdb, 0x76, 0x17,
	0x3b, 0x4e, 0x28, 0x52, 0x55, 0x3b, 0x77, 0x93, 0x8b, 0x96, 0x6d, 0xb7, 0x1c, 0x27, 0x34, 0x9e,
	0xc1, 0xea, 0xbc, 0xa4, 0x4a, 0x6f, 0x31, 0xa9, 0xf7, 0xe1, 0xbe, 0xc0, 0x7f, 0xe9, 0x3b, 0x64,
	0x40, 0x5c, 0xd9, 0x95, 0x7d, 0xfa, 0x19, 0xe6, 0x51, 0x48, 0xca, 0xf5, 0xb4, 0x95, 0x9e, 0x3c,
	0x54, 0xe0, 0x3c, 0x3e, 0xbe, 0xa4, 0xe7, 0x75, 0x80, 0x90, 0xd8, 0x34, 0x74, 0xba, 0xdf, 0x92,
	0xb1, 0x12, 0x52, 0x95, 0x27, 0xdb, 0x64, 0x9c, 0x4a, 0x28, 0xc9, 0x53, 0x2a, 0xe1, 0x1d, 0xb8,
	0x27, 0xf0, 0x5f, 0xe1, 0x81, 0xe7, 0xc4, 0x6f, 0x90, 0xd4, 0x5d, 0x82, 0xaa, 0x4d, 0x7d, 0x96,
	0x7f, 0xbf, 0x17, 0xe3, 0x03, 0xf1, 0x70, 0xdf, 0xc0, 0xab, 0x57, 0x51, 0xaa, 0x4a, 0x1b, 0xaa,
	0xa3, 0xe4, 0x50, 0xcd, 0xc6, 0x83, 0xe2, 0xd9, 0xd8, 0x4a, 0x0e, 0xb3, 0x24, 0x19, 0xd4, 0xb0,
	0x61, 0x51, 0x54, 0x68, 0x0d, 0x06, 0xe9, 0x7d, 0x32, 0x94, 0xa8, 0x0d, 0x90, 0xad, 0x95, 0xaa,
	0xb2, 0x6a, 0xca, 0xbd, 0x32, 0xe3, 0x1d, 0x34, 0xe5, 0x4e, 0xa9, 0x1d, 0x34, 0x77, 0xb1, 0x9b,
	0xb4, 0xa3, 0x93, 0x43, 0x1a, 0xbf, 0x6a, 0xa0, 0x17, 0x55, 0x51, 0x5a, 0x3e, 0x07, 0x48, 0x09,
	0xc5, 0x83, 0x7e, 0xfb, 0xff, 0x88, 0x51, 0x43, 0x9f, 0xcb, 0x80, 0x36, 0x2f, 0xd1, 0xbe, 0x25,
	0x68, 0xbf, 0x35, 0x97, 0xb6, 0x24, 0x93, 0xe7, 0xbd, 0x7e, 0x0a, 0x70, 0x47, 0xf0, 0x46, 0x27,
	0x1a, 0x2c, 0xc8, 0x25, 0x43, 0x33, 0x98, 0x5d, 0xdf, 0x69, 0xfd, 0xe1, 0x0d, 0x22, 0x65, 0x55,
	0xe3, 0xe1, 0xc9, 0x3f, 0xbf, 0xac, 0x69, 0xdf, 0xff, 0xfe, 0xf7, 0x8f, 0xb7, 0xea, 0x68, 0xd9,
	0x2a, 0x71, 0x11, 0xf4, 0xb3, 0x06, 0x77, 0xaf, 0xac, 0x34, 0x6a, 0x96, 0x54, 0x2a, 0x5e, 0x7f,
	0x7d, 0xb5, 0x18, 0xd2, 0xb2, 0x6d, 0x1a, 0xf9, 0x3c, 0x9e, 0x3e, 0xc2, 0x18, 0x61, 0xc6, 0xc7,
	0x19, 0xb3, 0x75, 0xf4, 0xb8, 0x98, 0x19, 0x0d, 0x78, 0x97, 0x46, 0x9c, 0x75, 0x39, 0xed, 0x1e,
	0x88, 0x2a, 0xd6, 0xb1, 0x18, 0xfb, 0x09, 0xfa, 0x57, 0x83, 0xc5, 0x99, 0x6b, 0x8f, 0x3e, 0x2c,
	0xe5, 0x5d, 0xee, 0x40, 0xfa, 0x47, 0xcf, 0x07, 0x56, 0x2f, 0xbe, 0x9f, 0xe9, 0xda, 0x42, 0x9b,
	0xb3, 0x74, 0x29, 0x83, 0x53, 0x02, 0x95, 0xb8, 0xae, 0xd0, 0x66, 0x1d, 0x5f, 0xf3, 0xbf, 0x09,
	0xfa, 0x4d, 0x83, 0x7b, 0x85, 0x2e, 0x85, 0x9e, 0x96, 0xb0, 0x2d, 0xf3, 0x35, 0xfd, 0xed, 0x62,
	0x60, 0x1e, 0xd3, 0x49, 0x6c, 0x8a, 0x19, 0x1b, 0x99, 0xac, 0xa7, 0xe8, 0xdd, 0x62, 0x59, 0x51,
	0xbe, 0x5c, 0xdc, 0xb3, 0xa1, 0x28, 0x98, 0xf6, 0x6c, 0xaa, 0xc1, 0xe2, 0x4c, 0x9f, 0x2b, 0xed,
	0xd9, 0x3c, 0x97, 0x2d, 0xed, 0xd9, 0x5c, 0x6b, 0x35, 0xb6, 0x33, 0x71, 0x9f, 0xa0, 0x67, 0xf3,
	0xc5, 0x49, 0x61, 0x1e, 0x1f, 0x27, 0x1d, 0xcb, 0x1c, 0x7e, 0x82, 0x7e, 0xd2, 0xa0, 0x9a, 0xba,
	0x08, 0x7a, 0x54, 0x42, 0xec, 0xaa, 0x67, 0xcf, 0x6a, 0x49, 0xb1, 0x55, 0x1b, 0xef, 0x65, 0xac,
	0x1b, 0xe8, 0x51, 0x31, 0xeb, 0xd4, 0xbd, 0xac, 0xe3, 0xf4, 0xbf, 0xc1, 0x04, 0x9d, 0x6a, 0x00,
	0x99, 0x5f, 0x22, 0xab, 0xa4, 0x6c, 0x91, 0x7f, 0xeb, 0x8f, 0x6f, 0x0e, 0x50, 0x5c, 0x1b, 0x19,
	0x57, 0x03, 0xad, 0xcc, 0xe1, 0xca, 0x36, 0x36, 0xcf, 0x2e, 0xea, 0xda, 0xf9, 0x45, 0x5d, 0xfb,
	0xeb, 0xa2, 0xae, 0xfd, 0x30, 0xad, 0x57, 0xce, 0xa7, 0xf5, 0xca, 0x1f, 0xd3, 0x7a, 0xe5, 0xeb,
	0x86, 0xeb, 0xf1, 0x7e, 0xd4, 0x33, 0x6d, 0x3a, 0x14, 0x59, 0x1a, 0x47, 0xe3, 0xef, 0x72, 0xe9,
	0x8e, 0xd2, 0x84, 0x7c, 0x1c, 0x10, 0xd6, 0x5b, 0x10, 0xbf, 0x8d, 0x9e, 0xfc, 0x17, 0x00, 0x00,
	0xff, 0xff, 0x74, 0x67, 0xe4, 0x19, 0x19, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Params queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// OptOutsToFinish queries the operators whose opt-outs will finish at the given epoch.
	OptOutsToFinish(ctx context.Context, in *QueryOptOutsToFinishRequest, opts ...grpc.CallOption) (*AccountAddresses, error)
	// OperatorOptOutFinishEpoch queries the epoch when the operator's opt-out will finish.
	OperatorOptOutFinishEpoch(ctx context.Context, in *QueryOperatorOptOutFinishEpochRequest, opts ...grpc.CallOption) (*QueryOperatorOptOutFinishEpochResponse, error)
	// UndelegationsToMature queries the undelegations that will mature at the given epoch.
	UndelegationsToMature(ctx context.Context, in *QueryUndelegationsToMatureRequest, opts ...grpc.CallOption) (*UndelegationRecordKeys, error)
	// UndelegationMaturityEpoch queries the epoch when the undelegation will mature.
	UndelegationMaturityEpoch(ctx context.Context, in *QueryUndelegationMaturityEpochRequest, opts ...grpc.CallOption) (*QueryUndelegationMaturityEpochResponse, error)
	// Validator queries the validator for the given consensus address. This is the bare-minimum validator:
	// public key, consensus address, power. No other params such as commission, jailed, etc. are included.
	Validator(ctx context.Context, in *QueryValidatorRequest, opts ...grpc.CallOption) (*QueryValidatorResponse, error)
	// Validators queries all validators. This is the bare-minimum validator: public key, consensus address, power.
	// No other params such as commission, jailed, etc. are included.
	Validators(ctx context.Context, in *QueryAllValidatorsRequest, opts ...grpc.CallOption) (*QueryAllValidatorsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/imuachain.dogfood.v1.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OptOutsToFinish(ctx context.Context, in *QueryOptOutsToFinishRequest, opts ...grpc.CallOption) (*AccountAddresses, error) {
	out := new(AccountAddresses)
	err := c.cc.Invoke(ctx, "/imuachain.dogfood.v1.Query/OptOutsToFinish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) OperatorOptOutFinishEpoch(ctx context.Context, in *QueryOperatorOptOutFinishEpochRequest, opts ...grpc.CallOption) (*QueryOperatorOptOutFinishEpochResponse, error) {
	out := new(QueryOperatorOptOutFinishEpochResponse)
	err := c.cc.Invoke(ctx, "/imuachain.dogfood.v1.Query/OperatorOptOutFinishEpoch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UndelegationsToMature(ctx context.Context, in *QueryUndelegationsToMatureRequest, opts ...grpc.CallOption) (*UndelegationRecordKeys, error) {
	out := new(UndelegationRecordKeys)
	err := c.cc.Invoke(ctx, "/imuachain.dogfood.v1.Query/UndelegationsToMature", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) UndelegationMaturityEpoch(ctx context.Context, in *QueryUndelegationMaturityEpochRequest, opts ...grpc.CallOption) (*QueryUndelegationMaturityEpochResponse, error) {
	out := new(QueryUndelegationMaturityEpochResponse)
	err := c.cc.Invoke(ctx, "/imuachain.dogfood.v1.Query/UndelegationMaturityEpoch", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Validator(ctx context.Context, in *QueryValidatorRequest, opts ...grpc.CallOption) (*QueryValidatorResponse, error) {
	out := new(QueryValidatorResponse)
	err := c.cc.Invoke(ctx, "/imuachain.dogfood.v1.Query/Validator", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Validators(ctx context.Context, in *QueryAllValidatorsRequest, opts ...grpc.CallOption) (*QueryAllValidatorsResponse, error) {
	out := new(QueryAllValidatorsResponse)
	err := c.cc.Invoke(ctx, "/imuachain.dogfood.v1.Query/Validators", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Params queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// OptOutsToFinish queries the operators whose opt-outs will finish at the given epoch.
	OptOutsToFinish(context.Context, *QueryOptOutsToFinishRequest) (*AccountAddresses, error)
	// OperatorOptOutFinishEpoch queries the epoch when the operator's opt-out will finish.
	OperatorOptOutFinishEpoch(context.Context, *QueryOperatorOptOutFinishEpochRequest) (*QueryOperatorOptOutFinishEpochResponse, error)
	// UndelegationsToMature queries the undelegations that will mature at the given epoch.
	UndelegationsToMature(context.Context, *QueryUndelegationsToMatureRequest) (*UndelegationRecordKeys, error)
	// UndelegationMaturityEpoch queries the epoch when the undelegation will mature.
	UndelegationMaturityEpoch(context.Context, *QueryUndelegationMaturityEpochRequest) (*QueryUndelegationMaturityEpochResponse, error)
	// Validator queries the validator for the given consensus address. This is the bare-minimum validator:
	// public key, consensus address, power. No other params such as commission, jailed, etc. are included.
	Validator(context.Context, *QueryValidatorRequest) (*QueryValidatorResponse, error)
	// Validators queries all validators. This is the bare-minimum validator: public key, consensus address, power.
	// No other params such as commission, jailed, etc. are included.
	Validators(context.Context, *QueryAllValidatorsRequest) (*QueryAllValidatorsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) OptOutsToFinish(ctx context.Context, req *QueryOptOutsToFinishRequest) (*AccountAddresses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OptOutsToFinish not implemented")
}
func (*UnimplementedQueryServer) OperatorOptOutFinishEpoch(ctx context.Context, req *QueryOperatorOptOutFinishEpochRequest) (*QueryOperatorOptOutFinishEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperatorOptOutFinishEpoch not implemented")
}
func (*UnimplementedQueryServer) UndelegationsToMature(ctx context.Context, req *QueryUndelegationsToMatureRequest) (*UndelegationRecordKeys, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndelegationsToMature not implemented")
}
func (*UnimplementedQueryServer) UndelegationMaturityEpoch(ctx context.Context, req *QueryUndelegationMaturityEpochRequest) (*QueryUndelegationMaturityEpochResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UndelegationMaturityEpoch not implemented")
}
func (*UnimplementedQueryServer) Validator(ctx context.Context, req *QueryValidatorRequest) (*QueryValidatorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validator not implemented")
}
func (*UnimplementedQueryServer) Validators(ctx context.Context, req *QueryAllValidatorsRequest) (*QueryAllValidatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validators not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imuachain.dogfood.v1.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OptOutsToFinish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOptOutsToFinishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OptOutsToFinish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imuachain.dogfood.v1.Query/OptOutsToFinish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OptOutsToFinish(ctx, req.(*QueryOptOutsToFinishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_OperatorOptOutFinishEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryOperatorOptOutFinishEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).OperatorOptOutFinishEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imuachain.dogfood.v1.Query/OperatorOptOutFinishEpoch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).OperatorOptOutFinishEpoch(ctx, req.(*QueryOperatorOptOutFinishEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UndelegationsToMature_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUndelegationsToMatureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UndelegationsToMature(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imuachain.dogfood.v1.Query/UndelegationsToMature",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UndelegationsToMature(ctx, req.(*QueryUndelegationsToMatureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_UndelegationMaturityEpoch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUndelegationMaturityEpochRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).UndelegationMaturityEpoch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imuachain.dogfood.v1.Query/UndelegationMaturityEpoch",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).UndelegationMaturityEpoch(ctx, req.(*QueryUndelegationMaturityEpochRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Validator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryValidatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Validator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imuachain.dogfood.v1.Query/Validator",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Validator(ctx, req.(*QueryValidatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Validators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllValidatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Validators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imuachain.dogfood.v1.Query/Validators",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Validators(ctx, req.(*QueryAllValidatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "imuachain.dogfood.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "OptOutsToFinish",
			Handler:    _Query_OptOutsToFinish_Handler,
		},
		{
			MethodName: "OperatorOptOutFinishEpoch",
			Handler:    _Query_OperatorOptOutFinishEpoch_Handler,
		},
		{
			MethodName: "UndelegationsToMature",
			Handler:    _Query_UndelegationsToMature_Handler,
		},
		{
			MethodName: "UndelegationMaturityEpoch",
			Handler:    _Query_UndelegationMaturityEpoch_Handler,
		},
		{
			MethodName: "Validator",
			Handler:    _Query_Validator_Handler,
		},
		{
			MethodName: "Validators",
			Handler:    _Query_Validators_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imuachain/dogfood/v1/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryOptOutsToFinishRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOptOutsToFinishRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOptOutsToFinishRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryOperatorOptOutFinishEpochRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOperatorOptOutFinishEpochRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOperatorOptOutFinishEpochRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.OperatorAccAddr) > 0 {
		i -= len(m.OperatorAccAddr)
		copy(dAtA[i:], m.OperatorAccAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OperatorAccAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryOperatorOptOutFinishEpochResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryOperatorOptOutFinishEpochResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryOperatorOptOutFinishEpochResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryUndelegationsToMatureRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUndelegationsToMatureRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUndelegationsToMatureRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryUndelegationMaturityEpochRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUndelegationMaturityEpochRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUndelegationMaturityEpochRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RecordKey) > 0 {
		i -= len(m.RecordKey)
		copy(dAtA[i:], m.RecordKey)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RecordKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryUndelegationMaturityEpochResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryUndelegationMaturityEpochResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryUndelegationMaturityEpochResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Epoch != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ConsAddr) > 0 {
		i -= len(m.ConsAddr)
		copy(dAtA[i:], m.ConsAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ConsAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryValidatorResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryValidatorResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryValidatorResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Validator != nil {
		{
			size, err := m.Validator.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllValidatorsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllValidatorsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllValidatorsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllValidatorsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllValidatorsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllValidatorsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Validators) > 0 {
		for iNdEx := len(m.Validators) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Validators[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryOptOutsToFinishRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovQuery(uint64(m.Epoch))
	}
	return n
}

func (m *QueryOperatorOptOutFinishEpochRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OperatorAccAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryOperatorOptOutFinishEpochResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovQuery(uint64(m.Epoch))
	}
	return n
}

func (m *QueryUndelegationsToMatureRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovQuery(uint64(m.Epoch))
	}
	return n
}

func (m *QueryUndelegationMaturityEpochRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RecordKey)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryUndelegationMaturityEpochResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Epoch != 0 {
		n += 1 + sovQuery(uint64(m.Epoch))
	}
	return n
}

func (m *QueryValidatorRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ConsAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryValidatorResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Validator != nil {
		l = m.Validator.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllValidatorsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllValidatorsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Validators) > 0 {
		for _, e := range m.Validators {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOptOutsToFinishRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOptOutsToFinishRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOptOutsToFinishRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOperatorOptOutFinishEpochRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOperatorOptOutFinishEpochRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOperatorOptOutFinishEpochRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OperatorAccAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OperatorAccAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryOperatorOptOutFinishEpochResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryOperatorOptOutFinishEpochResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryOperatorOptOutFinishEpochResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUndelegationsToMatureRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUndelegationsToMatureRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUndelegationsToMatureRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUndelegationMaturityEpochRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUndelegationMaturityEpochRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUndelegationMaturityEpochRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RecordKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RecordKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryUndelegationMaturityEpochResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryUndelegationMaturityEpochResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryUndelegationMaturityEpochResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ConsAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ConsAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryValidatorResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryValidatorResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryValidatorResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validator", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Validator == nil {
				m.Validator = &ImuachainValidator{}
			}
			if err := m.Validator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllValidatorsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllValidatorsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllValidatorsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllValidatorsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllValidatorsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllValidatorsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Validators", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Validators = append(m.Validators, ImuachainValidator{})
			if err := m.Validators[len(m.Validators)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
