// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: imuachain/avs/v1/fee.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// AVSPaymentInfo is avs payment records
type AVSPaymentInfo struct {
	// avs_address is the address of avs as a hex string
	AvsAddress string `protobuf:"bytes,1,opt,name=avs_address,json=avsAddress,proto3" json:"avs_address,omitempty"`
	// fee is Base fee (e.g., 1000 IMUA)
	Fee *types.Coin `protobuf:"bytes,2,opt,name=fee,proto3" json:"fee,omitempty"`
	// start_time is the start time of the avs payment
	StartTime int64 `protobuf:"varint,3,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// is_paid is whether the avs payment is paid or not
	IsPaid bool `protobuf:"varint,4,opt,name=is_paid,json=isPaid,proto3" json:"is_paid,omitempty"`
}

func (m *AVSPaymentInfo) Reset()         { *m = AVSPaymentInfo{} }
func (m *AVSPaymentInfo) String() string { return proto.CompactTextString(m) }
func (*AVSPaymentInfo) ProtoMessage()    {}
func (*AVSPaymentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d7b1077416be83fe, []int{0}
}
func (m *AVSPaymentInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AVSPaymentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AVSPaymentInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AVSPaymentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AVSPaymentInfo.Merge(m, src)
}
func (m *AVSPaymentInfo) XXX_Size() int {
	return m.Size()
}
func (m *AVSPaymentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AVSPaymentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AVSPaymentInfo proto.InternalMessageInfo

func (m *AVSPaymentInfo) GetAvsAddress() string {
	if m != nil {
		return m.AvsAddress
	}
	return ""
}

func (m *AVSPaymentInfo) GetFee() *types.Coin {
	if m != nil {
		return m.Fee
	}
	return nil
}

func (m *AVSPaymentInfo) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *AVSPaymentInfo) GetIsPaid() bool {
	if m != nil {
		return m.IsPaid
	}
	return false
}

func init() {
	proto.RegisterType((*AVSPaymentInfo)(nil), "imuachain.avs.v1.AVSPaymentInfo")
}

func init() { proto.RegisterFile("imuachain/avs/v1/fee.proto", fileDescriptor_d7b1077416be83fe) }

var fileDescriptor_d7b1077416be83fe = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xeb, 0xbf, 0xbf, 0x0a, 0x75, 0x25, 0x84, 0xb2, 0x10, 0x2a, 0x61, 0x22, 0xa6, 0x20,
	0x84, 0xad, 0xc0, 0x13, 0x94, 0x4e, 0x6c, 0x55, 0x40, 0x0c, 0x2c, 0xd5, 0x4d, 0xe2, 0x50, 0x0f,
	0x8e, 0xa3, 0x5c, 0xd7, 0x6a, 0x78, 0x0a, 0x26, 0x9e, 0x89, 0xb1, 0x23, 0x23, 0x4a, 0x5e, 0x04,
	0x25, 0x41, 0xb0, 0x9e, 0x7b, 0x8f, 0x3e, 0x9d, 0x8f, 0xce, 0x95, 0xde, 0x42, 0xba, 0x01, 0x55,
	0x08, 0x70, 0x28, 0x5c, 0x24, 0x72, 0x29, 0x79, 0x59, 0x19, 0x6b, 0xbc, 0xe3, 0xdf, 0x1b, 0x07,
	0x87, 0xdc, 0x45, 0x73, 0x96, 0x1a, 0xd4, 0x06, 0x45, 0x02, 0x28, 0x85, 0x8b, 0x12, 0x69, 0x21,
	0x12, 0xa9, 0x51, 0xc5, 0xd0, 0xb8, 0x78, 0x27, 0xf4, 0x68, 0xf1, 0xf4, 0xb0, 0x82, 0x5a, 0xcb,
	0xc2, 0xde, 0x17, 0xb9, 0xf1, 0xce, 0xe9, 0x0c, 0x1c, 0xae, 0x21, 0xcb, 0x2a, 0x89, 0xe8, 0x93,
	0x80, 0x84, 0xd3, 0x98, 0x82, 0xc3, 0xc5, 0x90, 0x78, 0x57, 0x74, 0x9c, 0x4b, 0xe9, 0xff, 0x0b,
	0x48, 0x38, 0xbb, 0x39, 0xe5, 0x03, 0x81, 0x77, 0x04, 0xfe, 0x43, 0xe0, 0x4b, 0xa3, 0x8a, 0xb8,
	0xfb, 0xf2, 0xce, 0x28, 0x45, 0x0b, 0x95, 0x5d, 0x5b, 0xa5, 0xa5, 0x3f, 0x0e, 0x48, 0x38, 0x8e,
	0xa7, 0x7d, 0xf2, 0xa8, 0xb4, 0xf4, 0x4e, 0xe8, 0x81, 0xc2, 0x75, 0x09, 0x2a, 0xf3, 0xff, 0x07,
	0x24, 0x3c, 0x8c, 0x27, 0x0a, 0x57, 0xa0, 0xb2, 0xbb, 0xe5, 0x47, 0xc3, 0xc8, 0xbe, 0x61, 0xe4,
	0xab, 0x61, 0xe4, 0xad, 0x65, 0xa3, 0x7d, 0xcb, 0x46, 0x9f, 0x2d, 0x1b, 0x3d, 0x5f, 0xbe, 0x28,
	0xbb, 0xd9, 0x26, 0x3c, 0x35, 0x5a, 0x74, 0x7b, 0xaf, 0x77, 0xf5, 0xab, 0xf8, 0x93, 0xb2, 0xeb,
	0xb5, 0xd8, 0xba, 0x94, 0x98, 0x4c, 0xfa, 0x91, 0xb7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcf,
	0xdd, 0x17, 0x38, 0x34, 0x01, 0x00, 0x00,
}

func (m *AVSPaymentInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AVSPaymentInfo) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AVSPaymentInfo) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsPaid {
		i--
		if m.IsPaid {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if m.StartTime != 0 {
		i = encodeVarintFee(dAtA, i, uint64(m.StartTime))
		i--
		dAtA[i] = 0x18
	}
	if m.Fee != nil {
		{
			size, err := m.Fee.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintFee(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.AvsAddress) > 0 {
		i -= len(m.AvsAddress)
		copy(dAtA[i:], m.AvsAddress)
		i = encodeVarintFee(dAtA, i, uint64(len(m.AvsAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintFee(dAtA []byte, offset int, v uint64) int {
	offset -= sovFee(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AVSPaymentInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AvsAddress)
	if l > 0 {
		n += 1 + l + sovFee(uint64(l))
	}
	if m.Fee != nil {
		l = m.Fee.Size()
		n += 1 + l + sovFee(uint64(l))
	}
	if m.StartTime != 0 {
		n += 1 + sovFee(uint64(m.StartTime))
	}
	if m.IsPaid {
		n += 2
	}
	return n
}

func sovFee(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozFee(x uint64) (n int) {
	return sovFee(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AVSPaymentInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowFee
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AVSPaymentInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AVSPaymentInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvsAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AvsAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fee", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthFee
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthFee
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Fee == nil {
				m.Fee = &types.Coin{}
			}
			if err := m.Fee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			m.StartTime = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartTime |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsPaid", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowFee
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsPaid = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipFee(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthFee
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipFee(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowFee
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFee
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowFee
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthFee
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupFee
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthFee
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthFee        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowFee          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupFee = fmt.Errorf("proto: unexpected end of group")
)
