// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: imuachain/evm/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	types "github.com/evmos/evmos/v16/x/evm/types"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MsgCallContract defines the request structure for executing a CallContract
// message.
type MsgCallContract struct {
	// authority is the calling + controlling address
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	// to is the hex address of the contract to call, or empty for contract creation
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// data is the raw call data bytes to be sent to the contract.
	Data []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// gas_limit is the gas limit for the transaction
	GasLimit uint64 `protobuf:"varint,4,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	// value is the value to send to the contract
	Amount *github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,5,opt,name=value,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"value,omitempty"`
}

func (m *MsgCallContract) Reset()         { *m = MsgCallContract{} }
func (m *MsgCallContract) String() string { return proto.CompactTextString(m) }
func (*MsgCallContract) ProtoMessage()    {}
func (*MsgCallContract) Descriptor() ([]byte, []int) {
	return fileDescriptor_283f3a78fc3f616f, []int{0}
}
func (m *MsgCallContract) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCallContract) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCallContract.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCallContract) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCallContract.Merge(m, src)
}
func (m *MsgCallContract) XXX_Size() int {
	return m.Size()
}
func (m *MsgCallContract) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCallContract.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCallContract proto.InternalMessageInfo

func (m *MsgCallContract) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgCallContract) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *MsgCallContract) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *MsgCallContract) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgCallContract)(nil), "imuachain.evm.v1.MsgCallContract")
}

func init() { proto.RegisterFile("imuachain/evm/v1/tx.proto", fileDescriptor_283f3a78fc3f616f) }

var fileDescriptor_283f3a78fc3f616f = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xbd, 0x6e, 0x13, 0x41,
	0x10, 0xf6, 0x39, 0x76, 0x14, 0xaf, 0x2c, 0x7e, 0x96, 0x48, 0x5c, 0xae, 0x38, 0x1b, 0x8a, 0xe0,
	0x58, 0xf2, 0xae, 0x02, 0x88, 0x82, 0x2e, 0xb6, 0x10, 0x02, 0x91, 0xe6, 0xa0, 0x4a, 0x13, 0x6d,
	0xec, 0xd5, 0xde, 0x0a, 0xef, 0xae, 0x75, 0x3b, 0x77, 0xb2, 0xa9, 0x10, 0x25, 0xa2, 0xe0, 0x51,
	0x5c, 0xf0, 0x10, 0x94, 0x11, 0x15, 0xa2, 0xb0, 0xd0, 0xb9, 0xf0, 0x6b, 0xa0, 0xfb, 0x21, 0x76,
	0xae, 0xd9, 0x9d, 0x99, 0x6f, 0xbe, 0x9d, 0xf9, 0x66, 0x16, 0x1d, 0x49, 0x15, 0xb3, 0x71, 0xc8,
	0xa4, 0xa6, 0x3c, 0x51, 0x34, 0x39, 0xa5, 0x30, 0x27, 0xb3, 0xc8, 0x80, 0xc1, 0xf7, 0x6e, 0x20,
	0xc2, 0x13, 0x45, 0x92, 0x53, 0xef, 0x3e, 0x53, 0x52, 0x1b, 0x9a, 0x9f, 0x45, 0x92, 0xf7, 0x70,
	0x6c, 0xac, 0x32, 0x96, 0x2a, 0x2b, 0x32, 0xb2, 0xb2, 0xa2, 0x04, 0x8e, 0x0a, 0xe0, 0x32, 0xf7,
	0x68, 0xe1, 0xfc, 0x87, 0x38, 0x84, 0x3c, 0x52, 0x52, 0x43, 0xb5, 0xa6, 0x77, 0x28, 0x8c, 0x30,
	0x05, 0x25, 0xb3, 0x8a, 0xe8, 0xe3, 0x6f, 0x75, 0x74, 0xf7, 0xdc, 0x8a, 0x11, 0x9b, 0x4e, 0x47,
	0x46, 0x43, 0xc4, 0xc6, 0x80, 0x5f, 0xa0, 0x16, 0x8b, 0x21, 0x34, 0x91, 0x84, 0x85, 0xeb, 0x74,
	0x9d, 0x5e, 0x6b, 0xe8, 0xfe, 0xfa, 0x31, 0x38, 0x2c, 0x2b, 0x9d, 0x4d, 0x26, 0x11, 0xb7, 0xf6,
	0x3d, 0x44, 0x52, 0x8b, 0x60, 0x9b, 0x8a, 0xef, 0xa0, 0x3a, 0x18, 0xb7, 0x9e, 0x11, 0x82, 0x3a,
	0x18, 0x8c, 0x51, 0x63, 0xc2, 0x80, 0xb9, 0x7b, 0x5d, 0xa7, 0xd7, 0x0e, 0x72, 0x1b, 0x9f, 0xa0,
	0x96, 0x60, 0xf6, 0x72, 0x2a, 0x95, 0x04, 0xb7, 0xd1, 0x75, 0x7a, 0x8d, 0x61, 0x3b, 0x5d, 0x75,
	0x0e, 0x5e, 0x33, 0xfb, 0x2e, 0x8b, 0x05, 0x07, 0xa2, 0xb4, 0xf0, 0x5b, 0xd4, 0x4c, 0xd8, 0x34,
	0xe6, 0x6e, 0x33, 0x6f, 0xe1, 0xf9, 0x9f, 0x55, 0xe7, 0x58, 0x48, 0x08, 0xe3, 0x2b, 0x32, 0x36,
	0xaa, 0xd4, 0x5d, 0x5e, 0x03, 0x3b, 0xf9, 0x48, 0x61, 0x31, 0xe3, 0x96, 0xbc, 0xd1, 0x90, 0xae,
	0x3a, 0xfb, 0x67, 0xca, 0xc4, 0x1a, 0x82, 0xe2, 0x89, 0x97, 0xc7, 0x5f, 0x36, 0xcb, 0xfe, 0xb6,
	0xd5, 0xaf, 0x9b, 0x65, 0xff, 0x41, 0x36, 0xa0, 0x8a, 0xf4, 0xa7, 0x21, 0xda, 0x3b, 0xb7, 0x02,
	0x5f, 0xa0, 0xf6, 0xad, 0x89, 0x3c, 0x22, 0xd5, 0x85, 0x91, 0x0a, 0xd3, 0x7b, 0x42, 0x6e, 0x46,
	0xbf, 0x93, 0xf2, 0x2a, 0x8b, 0xf1, 0x58, 0x7d, 0x98, 0x07, 0xdc, 0xce, 0x8c, 0xb6, 0xdc, 0x6b,
	0x7e, 0xde, 0x2c, 0xfb, 0xce, 0x70, 0xf4, 0x33, 0xf5, 0x9d, 0xeb, 0xd4, 0x77, 0xfe, 0xa6, 0xbe,
	0xf3, 0x7d, 0xed, 0xd7, 0xae, 0xd7, 0x7e, 0xed, 0xf7, 0xda, 0xaf, 0x5d, 0x9c, 0xec, 0x88, 0xcc,
	0xca, 0x0e, 0xe6, 0x8b, 0x4f, 0x74, 0xfb, 0x97, 0xe6, 0xf9, 0x66, 0x73, 0xad, 0x57, 0xfb, 0xf9,
	0x12, 0x9f, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x88, 0x2c, 0xe3, 0x82, 0x6b, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// CallContract defines a message that can be called by the module's
	// authority to call a contract. While it is technically feasible
	// for any Cosmos address to call an x/evm contract, we intentionally
	// restrict this functionality to the module's authority. It is used
	// by the authority to manage the ImuachainGateway contract.
	CallContract(ctx context.Context, in *MsgCallContract, opts ...grpc.CallOption) (*types.MsgEthereumTxResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CallContract(ctx context.Context, in *MsgCallContract, opts ...grpc.CallOption) (*types.MsgEthereumTxResponse, error) {
	out := new(types.MsgEthereumTxResponse)
	err := c.cc.Invoke(ctx, "/imuachain.evm.v1.Msg/CallContract", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// CallContract defines a message that can be called by the module's
	// authority to call a contract. While it is technically feasible
	// for any Cosmos address to call an x/evm contract, we intentionally
	// restrict this functionality to the module's authority. It is used
	// by the authority to manage the ImuachainGateway contract.
	CallContract(context.Context, *MsgCallContract) (*types.MsgEthereumTxResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CallContract(ctx context.Context, req *MsgCallContract) (*types.MsgEthereumTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CallContract not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CallContract_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCallContract)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CallContract(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/imuachain.evm.v1.Msg/CallContract",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CallContract(ctx, req.(*MsgCallContract))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "imuachain.evm.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CallContract",
			Handler:    _Msg_CallContract_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "imuachain/evm/v1/tx.proto",
}

func (m *MsgCallContract) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCallContract) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCallContract) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != nil {
		{
			size := m.Amount.Size()
			i -= size
			if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.GasLimit != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.GasLimit))
		i--
		dAtA[i] = 0x20
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintTx(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCallContract) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.GasLimit != 0 {
		n += 1 + sovTx(uint64(m.GasLimit))
	}
	if m.Amount != nil {
		l = m.Amount.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCallContract) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCallContract: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCallContract: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			m.GasLimit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.GasLimit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Int
			m.Amount = &v
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
