package keeper

import (
	"strings"

	epochstypes "github.com/ExocoreNetwork/exocore/x/epochs/types"
	sdk "github.com/cosmos/cosmos-sdk/types"
)

// EpochsHooksWrapper is the wrapper structure that implements the epochs hooks for the avs
// keeper.
type EpochsHooksWrapper struct {
	keeper *Keeper
}

// Interface guard
var _ epochstypes.EpochHooks = EpochsHooksWrapper{}

// EpochsHooks returns the epochs hooks wrapper.
func (k *Keeper) EpochsHooks() EpochsHooksWrapper {
	return EpochsHooksWrapper{k}
}

// BeforeEpochStart: noop, We don't need to do anything here
func (wrapper EpochsHooksWrapper) BeforeEpochStart(_ sdk.Context, _ string, _ int64) {
}

// AfterEpochEnd mints and allocates coins at the end of each epoch end
func (wrapper EpochsHooksWrapper) AfterEpochEnd(ctx sdk.Context, epochIdentifier string, _ int64) {
	expEpochID := wrapper.keeper.GetParams(ctx).EpochIdentifier
	if strings.Compare(epochIdentifier, expEpochID) == 0 {
		// the minted coins generated by minting module will do the token allocation and distribution here
		// previousTotalPower := wrapper.keeper.StakingKeeper.GetLastTotalPower(ctx)
		logger := wrapper.keeper.Logger()
		logger.Info(
			"AfterEpochEnd of distribution",
		)
		// at the end of an epoch we distribute all minted tokens for one epoch and left fees
		// here we have the temporary approach that we allocate minited tokens for next epoch then we can correctly
		// distribute those tokens based on potential slash event. And that should be ok since the amount of minited
		// token for each epoch is the same, so we just missed the very first epoch's minting.
		if err := wrapper.keeper.AllocateTokens(ctx, false); err != nil {
			logger.Error("failed to allocate tokens", "err", err)
		}
	}
}
